// Les textes de la page d'invitation, dans les dix langues.
//
// La page n'a qu'une adresse (dropletmesh.app/i/), parce que le lien est
// fabriqué par l'application de celui qui invite, sans savoir quelle langue
// lit celui qui le reçoit. C'est donc le navigateur de l'invité qui choisit
// la langue, au chargement. « {nom} » est remplacé par le pseudo.
export const TEXTES_INVITATION = {
  fr: {
    titre: '{nom} vous invite sur Droplet',
    titreSansNom: 'Vous êtes invité sur Droplet',
    texte: 'La messagerie qui marche même sans réseau. Vos messages sont chiffrés de bout en bout.',
    ouvrir: 'Ouvrir dans Droplet',
    telecharger: 'Télécharger Droplet',
    pasEncore: "Vous n'avez pas encore Droplet ?",
    etapes: ['Installez Droplet.', 'Revenez sur ce lien.', 'Touchez « Ouvrir dans Droplet ».'],
    prive: "Ce lien n'est envoyé à aucun serveur : l'invitation reste sur votre téléphone.",
    invalide: "Ce lien d'invitation est incomplet. Demandez-en un nouveau à la personne qui vous l'a envoyé.",
    bureau: 'Ouvrez ce lien sur votre téléphone Android pour accepter l’invitation.',
    decouvrir: 'Découvrir Droplet',
  },
  en: {
    titre: '{nom} invited you to Droplet',
    titreSansNom: "You're invited to Droplet",
    texte: 'The messenger that works even without a network. Your messages are end-to-end encrypted.',
    ouvrir: 'Open in Droplet',
    telecharger: 'Download Droplet',
    pasEncore: "Don't have Droplet yet?",
    etapes: ['Install Droplet.', 'Come back to this link.', 'Tap “Open in Droplet”.'],
    prive: 'This link is never sent to a server: the invitation stays on your phone.',
    invalide: 'This invitation link is incomplete. Ask the person who sent it for a new one.',
    bureau: 'Open this link on your Android phone to accept the invitation.',
    decouvrir: 'Discover Droplet',
  },
  de: {
    titre: '{nom} lädt Sie zu Droplet ein',
    titreSansNom: 'Sie sind zu Droplet eingeladen',
    texte: 'Der Messenger, der auch ohne Netz funktioniert. Ihre Nachrichten sind Ende-zu-Ende-verschlüsselt.',
    ouvrir: 'In Droplet öffnen',
    telecharger: 'Droplet laden',
    pasEncore: 'Sie haben Droplet noch nicht?',
    etapes: ['Installieren Sie Droplet.', 'Öffnen Sie diesen Link erneut.', 'Tippen Sie auf „In Droplet öffnen“.'],
    prive: 'Dieser Link wird an keinen Server gesendet: Die Einladung bleibt auf Ihrem Telefon.',
    invalide: 'Dieser Einladungslink ist unvollständig. Bitten Sie den Absender um einen neuen.',
    bureau: 'Öffnen Sie diesen Link auf Ihrem Android-Telefon, um die Einladung anzunehmen.',
    decouvrir: 'Droplet entdecken',
  },
  es: {
    titre: '{nom} te invita a Droplet',
    titreSansNom: 'Te han invitado a Droplet',
    texte: 'La mensajería que funciona incluso sin red. Tus mensajes están cifrados de extremo a extremo.',
    ouvrir: 'Abrir en Droplet',
    telecharger: 'Descargar Droplet',
    pasEncore: '¿Aún no tienes Droplet?',
    etapes: ['Instala Droplet.', 'Vuelve a este enlace.', 'Toca «Abrir en Droplet».'],
    prive: 'Este enlace no se envía a ningún servidor: la invitación se queda en tu teléfono.',
    invalide: 'Este enlace de invitación está incompleto. Pide uno nuevo a quien te lo envió.',
    bureau: 'Abre este enlace en tu teléfono Android para aceptar la invitación.',
    decouvrir: 'Descubre Droplet',
  },
  it: {
    titre: '{nom} ti invita su Droplet',
    titreSansNom: 'Sei stato invitato su Droplet',
    texte: 'La messaggistica che funziona anche senza rete. I tuoi messaggi sono crittografati end-to-end.',
    ouvrir: 'Apri in Droplet',
    telecharger: 'Scarica Droplet',
    pasEncore: 'Non hai ancora Droplet?',
    etapes: ['Installa Droplet.', 'Torna a questo link.', 'Tocca «Apri in Droplet».'],
    prive: "Questo link non viene inviato a nessun server: l'invito resta sul tuo telefono.",
    invalide: "Questo link d'invito è incompleto. Chiedine uno nuovo a chi te l'ha inviato.",
    bureau: "Apri questo link sul tuo telefono Android per accettare l'invito.",
    decouvrir: 'Scopri Droplet',
  },
  pt: {
    titre: '{nom} convidou você para o Droplet',
    titreSansNom: 'Você foi convidado para o Droplet',
    texte: 'O mensageiro que funciona até sem rede. Suas mensagens têm criptografia de ponta a ponta.',
    ouvrir: 'Abrir no Droplet',
    telecharger: 'Baixar o Droplet',
    pasEncore: 'Ainda não tem o Droplet?',
    etapes: ['Instale o Droplet.', 'Volte a este link.', 'Toque em “Abrir no Droplet”.'],
    prive: 'Este link não é enviado a nenhum servidor: o convite fica no seu celular.',
    invalide: 'Este link de convite está incompleto. Peça um novo a quem o enviou.',
    bureau: 'Abra este link no seu celular Android para aceitar o convite.',
    decouvrir: 'Conheça o Droplet',
  },
  ru: {
    titre: '{nom} приглашает вас в Droplet',
    titreSansNom: 'Вас пригласили в Droplet',
    texte: 'Мессенджер, который работает даже без сети. Ваши сообщения защищены сквозным шифрованием.',
    ouvrir: 'Открыть в Droplet',
    telecharger: 'Скачать Droplet',
    pasEncore: 'Ещё нет Droplet?',
    etapes: ['Установите Droplet.', 'Вернитесь к этой ссылке.', 'Нажмите «Открыть в Droplet».'],
    prive: 'Эта ссылка не отправляется ни на один сервер: приглашение остаётся на вашем телефоне.',
    invalide: 'Ссылка-приглашение неполная. Попросите отправителя прислать новую.',
    bureau: 'Откройте эту ссылку на телефоне Android, чтобы принять приглашение.',
    decouvrir: 'Узнать о Droplet',
  },
  zh: {
    titre: '{nom} 邀请你使用 Droplet',
    titreSansNom: '你收到了 Droplet 邀请',
    texte: '即使没有网络也能使用的通讯应用。你的消息经过端到端加密。',
    ouvrir: '在 Droplet 中打开',
    telecharger: '下载 Droplet',
    pasEncore: '还没有 Droplet？',
    etapes: ['安装 Droplet。', '回到这个链接。', '轻点“在 Droplet 中打开”。'],
    prive: '此链接不会发送到任何服务器：邀请只留在你的手机上。',
    invalide: '此邀请链接不完整。请向发送者索取新的链接。',
    bureau: '请在你的 Android 手机上打开此链接以接受邀请。',
    decouvrir: '了解 Droplet',
  },
  ar: {
    titre: 'يدعوك {nom} إلى Droplet',
    titreSansNom: 'لقد تلقيت دعوة إلى Droplet',
    texte: 'تطبيق المراسلة الذي يعمل حتى دون شبكة. رسائلك مشفّرة من طرف إلى طرف.',
    ouvrir: 'فتح في Droplet',
    telecharger: 'تنزيل Droplet',
    pasEncore: 'ليس لديك Droplet بعد؟',
    etapes: ['ثبّت Droplet.', 'عُد إلى هذا الرابط.', 'اضغط «فتح في Droplet».'],
    prive: 'لا يُرسَل هذا الرابط إلى أي خادم: تبقى الدعوة على هاتفك.',
    invalide: 'رابط الدعوة هذا غير مكتمل. اطلب رابطًا جديدًا من الشخص الذي أرسله.',
    bureau: 'افتح هذا الرابط على هاتف Android لقبول الدعوة.',
    decouvrir: 'اكتشف Droplet',
  },
  hi: {
    titre: '{nom} ने आपको Droplet पर बुलाया है',
    titreSansNom: 'आपको Droplet पर बुलाया गया है',
    texte: 'ऐसा मैसेंजर जो नेटवर्क के बिना भी काम करता है। आपके संदेश एंड-टू-एंड एन्क्रिप्टेड हैं।',
    ouvrir: 'Droplet में खोलें',
    telecharger: 'Droplet डाउनलोड करें',
    pasEncore: 'अभी तक Droplet नहीं है?',
    etapes: ['Droplet इंस्टॉल करें।', 'इस लिंक पर वापस आएँ।', '“Droplet में खोलें” पर टैप करें।'],
    prive: 'यह लिंक किसी सर्वर पर नहीं भेजा जाता: निमंत्रण आपके फ़ोन पर ही रहता है।',
    invalide: 'यह निमंत्रण लिंक अधूरा है। भेजने वाले से नया लिंक माँगें।',
    bureau: 'निमंत्रण स्वीकार करने के लिए यह लिंक अपने Android फ़ोन पर खोलें।',
    decouvrir: 'Droplet को जानें',
  },
} as const;
